### PR TITLE
moved back to light theme, added icons to lib

### PR DESCRIPTION
**Pull request by rowan-carlsen**
Restored the light theme, just started work on the dashboard.

### CODE REVIEW

**Review by arturparkhisenko — DISMISSED** [review]
@rowan-carlsen can you please move prod dependencies out of the devdeps into the dependencies list in the package.json? example: smui-theme and related things.

**Review by Ris345 — COMMENTED** [review]
@rowan-carlsen  once you push those changes we can merge it to the main branch.

**Comment by rowan-carlsen** [comment]
> @rowan-carlsen once you push those changes we can merge it to the main branch.

We discussed, the changes are not needed at this time. I’m on vacation until Thursday, so I would suggest merging this to remove blockers for other front end folks.

**Comment by Ris345** [comment]
@rowan-carlsen ok got it he still needs to review it let me slack him in order to merge

**Pull request merged**
