### PR TITLE
init backend with structure and tasks

### PR DESCRIPTION
**Pull request by PetN5026**
todo

### CODE REVIEW

**Review by Ris345 — CHANGES_REQUESTED** [review]
@PetN5026 Thank you for adding the gitignore file. I can merge it once you rename the app folder to server.

**Comment by ccelest1** [comment]
@PetN5026 I have some feedback regarding this PR

1. Upon an initial view of the current repo/outline of directories and files. Ideally we want it to be 

```md
/models
|--TasksModels.py (could just be tasks.py)
|--users (currently models.py on main branch)
/schemas
|--TaskSchema.py (could just be tasks.py)
..etc
````

the final structure being

```md
/internal
|--__init__.py
|--admin.py
/models
|-- events.py
|-- usersGroups.py
| -- tasks.py
/queries
/routes
/schemas
__init__.py
database.py
dependencies.py
main.py
```

I am going to be working with you to make sure we have the appropriate structure.

2. 
I see that you deleted the virtual environment or 'dependencies'. It is wise to actually use a virtual environment in our development just to make sure everyone is working on current versions of imports. We will have to discuss the use of (env) going forward. It may be as a result of a missing requirements file, that I pushed on my branch svelete/monolithic.

3.
In regards to actual code:
(models/TasksModels.py)
I believe that the Task model may need to be revised to ideally

```
class Task(Base):
__tablename__ = "tasks"
 id
 name
 owner
 description
 tasklist_id
 assignment/assigned_user
 type
 isCompleted
 date_created
 date_updated
```
I am not sure about the quantity or that will have to be discussed


4. For tasks schemas,
we will need a TaskBase, TaskCreate, TaskSchema

```
ModelBase - common attributes when creating or reading data

ModelCreate - inherit from BaseModel and include additional info for creation

ModelSchema - schemas used when reading data, when returning it from API
```

5. queries and routers seem quite good
two things
@router.post for tasks should be '/tasks'
```
@router.post('/tasks', response_model=TaskCreate)
def create_task(
 name: str = Form(...),
 etc {other applicable task fields for taskCreate Schema}
```

**Comment by PetN5026** [comment]
Are we going to use a python venv or docker.

**Review by Ris345 — COMMENTED** [review]
@PetN5026  Craig's comment explains the situation well. Let's get out structure together before we merge to the main branch :)

**Pull request closed without merging**
