### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by PetN5026**
#68 
Worked with Artur, Craig and got docker image to create and run Uvicorn server.

#74 

Created docker compose up file so front end can just run docker compose up at repo root to start the back end server. And docker compose down to turn it off.

### CODE REVIEW

**Review by ccelest1 — CHANGES_REQUESTED** [review]
@PetN5026 Please leave more information, perhaps in comments about new command to be ran regarding Docker.

Do I just run docker-compose and does this command essentially achieve the same results as prior? Dockerfile still contains old commands which I am assuming are replaced by what is to be one command.

Thank you.

**Comment by PetN5026** [comment]
Oops, I updated the readme with docker installation, and the commands to start and stop compose. I forgot to delete them from docker file

**Comment by PetN5026** [comment]
> @PetN5026 Please leave more information, perhaps in comments about new command to be ran regarding Docker.
> 
> Do I just run docker-compose and does this command essentially achieve the same results as prior? Dockerfile still contains old commands which I am assuming are replaced by what is to be one command.
> 
> Thank you.

Added commands also in DockerFile as comments now.

**Review by ccelest1 — APPROVED** [review]

**Comment by ccelest1** [comment]
Readme updated satisfactorily including Docker instructions `docker compose up (creates image, container)  -> localhost:8000/docs -> docker compose down (removes image, container` 👍

**Pull request merged**
